Repository Danny492/ClinicApp, pull requests merged in 2025-09, with the labels that each got.

#2 Feat: Implementación estructuración Vista de Gestión de Pacientes + Simulación CRUD
  src/app/layout/component/app.menu.ts
  src/app/pages/crud/crud.ts
  src/app/pages/paciente/paciente.ts
  src/app/pages/pages.routes.ts
  src/app/pages/service/patient.service.ts
  src/app/pages/uikit/overlaydemo.ts
  src/main.ts
Labels: Frontend, feature

#6 feat(doctores): implementar gestión de doctores con CRUD simulado y horarios disponibles #4
  src/app/layout/component/app.menu.ts
  src/app/pages/doctor/doctor.html
  src/app/pages/doctor/doctor.scss
  src/app/pages/doctor/doctor.ts
  src/app/pages/pages.routes.ts
  src/app/pages/service/doctor.service.ts
Labels: enhancement, Frontend, feature, priority-mid-level, module-doctors

#9 feat(dashboard): implementar la vista principal de la pagina
  src/app/pages/dashboard/components/revenuestreamwidget.ts
  src/app/pages/dashboard/components/statswidget.ts
  src/app/pages/dashboard/dashboard.ts
Labels: enhancement, good first issue, Frontend, feature, priority-high, dashboard, module-dashboard
